# Generated by Django 5.2.7 on 2025-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_order_status',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
