# Generated by Django 5.2.7 on 2025-12-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingproduct',
            name='category',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pents', 'Pents'), ('shalwar_kameez', 'Shalwar Kameez'), ('accessories', 'Accessories')], max_length=50),
        ),
    ]
